/****** Object:  Database [ShopBridgeDB]    Script Date: 04-10-2021 9.19.18 PM ******/
CREATE DATABASE [ShopBridgeDB]  (EDITION = 'GeneralPurpose', SERVICE_OBJECTIVE = 'GP_S_Gen5_1', MAXSIZE = 1 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO
ALTER DATABASE [ShopBridgeDB] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [ShopBridgeDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ShopBridgeDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ShopBridgeDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ShopBridgeDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ShopBridgeDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ShopBridgeDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ShopBridgeDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ShopBridgeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ShopBridgeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ShopBridgeDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ShopBridgeDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ShopBridgeDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ShopBridgeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ShopBridgeDB] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [ShopBridgeDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ShopBridgeDB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [ShopBridgeDB] SET  MULTI_USER 
GO
ALTER DATABASE [ShopBridgeDB] SET ENCRYPTION ON
GO
ALTER DATABASE [ShopBridgeDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [ShopBridgeDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
/*** The scripts of database scoped configurations in Azure should be executed inside the target database connection. ***/
GO
-- ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 8;
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 04-10-2021 9.19.18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Categories]    Script Date: 04-10-2021 9.19.18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[CategoryId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[CategoryId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 04-10-2021 9.19.18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Description] [varchar](250) NOT NULL,
	[UnitPrice] [decimal](18, 2) NOT NULL,
	[CategoryId] [int] NOT NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 04-10-2021 9.19.19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NULL,
	[Address] [nvarchar](max) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Products_CategoryId]    Script Date: 04-10-2021 9.19.19 PM ******/
CREATE NONCLUSTERED INDEX [IX_Products_CategoryId] ON [dbo].[Products]
(
	[CategoryId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Products_Categories_CategoryId] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([CategoryId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_Categories_CategoryId]
GO
/****** Object:  StoredProcedure [dbo].[usp_getproduct]    Script Date: 04-10-2021 9.19.19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[usp_getproduct]
@ProductId int
as
begin
	Select * from [dbo].[Products] where ProductId=@ProductId
end
GO
ALTER DATABASE [ShopBridgeDB] SET  READ_WRITE 
GO

INSERT [dbo].[Categories] ([Id], [Name], [Description]) VALUES (1, N'Books', N'Books')
